name: Build SQLite Libraries

on:
  push:
    branches: [main]
    paths:
      - 'packages/libsqlite3-*/build.sh'
      - '.github/workflows/build-sqlite.yml'
  pull_request:
    branches: [main]
    paths:
      - 'packages/libsqlite3-*/build.sh'
      - '.github/workflows/build-sqlite.yml'
  workflow_dispatch:

jobs:
  build-darwin-arm64:
    runs-on: macos-14  # M1 runner
    steps:
      - uses: actions/checkout@v4
      
      - name: Build SQLite for darwin-arm64
        run: |
          cd packages/libsqlite3-darwin-arm64
          ./build.sh
      
      - name: Verify build
        run: |
          cd packages/libsqlite3-darwin-arm64
          file vendor/libsqlite3.0.dylib
          otool -L vendor/libsqlite3.0.dylib
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libsqlite3-darwin-arm64
          path: |
            packages/libsqlite3-darwin-arm64/vendor/
            packages/libsqlite3-darwin-arm64/LICENSE.sqlite
          retention-days: 30

  build-darwin-x64:
    runs-on: macos-13  # Intel runner
    steps:
      - uses: actions/checkout@v4
      
      - name: Build SQLite for darwin-x64
        run: |
          cd packages/libsqlite3-darwin-x64
          ./build.sh
      
      - name: Verify build
        run: |
          cd packages/libsqlite3-darwin-x64
          file vendor/libsqlite3.0.dylib
          otool -L vendor/libsqlite3.0.dylib
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libsqlite3-darwin-x64
          path: |
            packages/libsqlite3-darwin-x64/vendor/
            packages/libsqlite3-darwin-x64/LICENSE.sqlite
          retention-days: 30
EOF < /dev/null